import { Stack } from 'expo-router';
import { StyleSheet } from 'react-native';

import Counter from '@/components/drill/case-2-counter';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';

// Stable harness screen — do not edit this file during the drill.
// Edit components/drill/case-2-counter.tsx instead and watch this render.
export default function Case2Screen() {
  return (
    <ThemedView style={styles.container}>
      <Stack.Screen options={{ title: 'Case 2' }} />
      <ThemedText type="subtitle">Case 2 — component + THEME constant</ThemedText>
      <ThemedText>
        Predicted: rule 2. The module isn&apos;t a safe boundary, so count
        resets on edits to case-2-counter.tsx.
      </ThemedText>
      <Counter />
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, gap: 12, padding: 24 },
});
