import { Stack } from 'expo-router';
import { StyleSheet } from 'react-native';

import Counter from '@/components/drill/case-1-counter';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';

// Stable harness screen — do not edit this file during the drill.
// Edit components/drill/case-1-counter.tsx instead and watch this render.
export default function Case1Screen() {
  return (
    <ThemedView style={styles.container}>
      <Stack.Screen options={{ title: 'Case 1' }} />
      <ThemedText type="subtitle">Case 1 — component-only export</ThemedText>
      <ThemedText>
        Predicted: rule 1. Count should survive edits to case-1-counter.tsx.
      </ThemedText>
      <Counter />
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, gap: 12, padding: 24 },
});
