import { Stack } from 'expo-router';
import { StyleSheet } from 'react-native';

import Counter from '@/components/drill/case-3-counter';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { describeTheme } from '@/lib/drill/theme-consumer';

// Stable harness screen — do not edit this file during the drill.
// Edit components/drill/case-3-counter.tsx instead and watch this render.
export default function Case3Screen() {
  return (
    <ThemedView style={styles.container}>
      <Stack.Screen options={{ title: 'Case 3' }} />
      <ThemedText type="subtitle">Case 3 — constant isolated (post-refactor)</ThemedText>
      <ThemedText>{describeTheme()}</ThemedText>
      <ThemedText>
        Fixed state: rule 1 applies again. See FINDINGS.md for the broken
        version this replaced and why it forced a full reload.
      </ThemedText>
      <Counter />
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, gap: 12, padding: 24 },
});
